<?php 
/* 	
If you see this text in your browser, PHP is not configured correctly on this hosting provider. 
Contact your hosting provider regarding PHP configuration for your site.

PHP file generated by Adobe Muse CC 2018.1.0.386
*/

require_once('form_process.php');

$form = array(
	'subject' => 'Registration Form Submission',
	'heading' => 'New Form Submission',
	'success_redirect' => 'registration2.html',
	'resources' => array(
		'checkbox_checked' => 'Checked',
		'checkbox_unchecked' => 'Unchecked',
		'submitted_from' => 'Form submitted from website: %s',
		'submitted_by' => 'Visitor IP address: %s',
		'too_many_submissions' => 'Too many recent submissions from this IP',
		'failed_to_send_email' => 'Failed to send email',
		'invalid_reCAPTCHA_private_key' => 'Invalid reCAPTCHA private key.',
		'invalid_reCAPTCHA2_private_key' => 'Invalid reCAPTCHA 2.0 private key.',
		'invalid_reCAPTCHA2_server_response' => 'Invalid reCAPTCHA 2.0 server response.',
		'invalid_field_type' => 'Unknown field type \'%s\'.',
		'invalid_form_config' => 'Field \'%s\' has an invalid configuration.',
		'unknown_method' => 'Unknown server request method'
	),
	'email' => array(
		'from' => 'prabhakar.npds@gmail.com',
		'to' => 'prabhakar.npds@gmail.com'
	),
	'fields' => array(
		'custom_U10602' => array(
			'order' => 1,
			'type' => 'string',
			'label' => 'Name: *',
			'required' => false,
			'errors' => array(
			)
		),
		'Email' => array(
			'order' => 2,
			'type' => 'email',
			'label' => 'Email (To be your Login Id): *',
			'required' => false,
			'errors' => array(
				'format' => 'Field \'Email (To be your Login Id): *\' has an invalid email.'
			)
		),
		'custom_U10630' => array(
			'order' => 5,
			'type' => 'string',
			'label' => 'Mobile  Number: *',
			'required' => false,
			'errors' => array(
			)
		),
		'custom_U10611' => array(
			'order' => 6,
			'type' => 'string',
			'label' => 'City: *',
			'required' => false,
			'errors' => array(
			)
		),
		'custom_U10634' => array(
			'order' => 7,
			'type' => 'string',
			'label' => 'Current State of residence: *',
			'required' => false,
			'errors' => array(
			)
		),
		'custom_U10626' => array(
			'order' => 8,
			'type' => 'string',
			'label' => 'Permanent State of residence: *',
			'required' => false,
			'errors' => array(
			)
		),
		'custom_U10619' => array(
			'order' => 3,
			'type' => 'string',
			'label' => 'Enter Password: *',
			'required' => false,
			'errors' => array(
			)
		),
		'custom_U10615' => array(
			'order' => 4,
			'type' => 'string',
			'label' => 'Re-enter Password: *',
			'required' => false,
			'errors' => array(
			)
		)
	)
);

process_form($form);
?>
